import {
    BaggageClaim,
    Beer,
    Cake,
    Candy,
    Carrot,
    Coffee,
    Fish,
    GlassWater,
    IceCream,
    LayoutPanelTop,
    Milk,
    Minus,
    Package,
    Pizza,
    Plus,
    Popcorn,
    ReceiptText,
    Sandwich,
    ShoppingCart,
    Soup,
    Table2,
    Tag,
    Users,
    Utensils,
    UtensilsCrossed,
    Wallet,
    X,
} from 'lucide-react';
import React, { SVGProps } from 'react';

export const LucideIconMap: { [key: string]: React.ElementType<SVGProps<SVGSVGElement>> } = {
    BaggageClaim: BaggageClaim,
    Beer: Beer,
    Cake: Cake,
    Candy: Candy,
    Carrot: Carrot,
    Coffee: Coffee,
    Fish: Fish,
    GlassWater: GlassWater,
    IceCream: IceCream,
    LayoutPanelTop: LayoutPanelTop,
    Milk: Milk,
    Minus: Minus,
    Package: Package,
    Pizza: Pizza,
    Plus: Plus,
    Popcorn: Popcorn,
    ReceiptText: ReceiptText,
    Sandwich: Sandwich,
    ShoppingCart: ShoppingCart,
    Soup: Soup,
    Table2: Table2,
    Tag: Tag,
    Users: Users,
    Utensils: Utensils,
    UtensilsCrossed: UtensilsCrossed,
    Wallet: Wallet,
    X: X,
    // Pastikan semua ikon yang Anda gunakan di `kategoris.icon` ada di sini
};
