// Generated by https://quicktype.io

export interface User {
    id: number;
    name: string;
    email: string;
    email_verified_at: null;
    phone: string;
    address: string;
    avatar: string;
    role: string;
    is_active: number;
    created_at: Date;
    updated_at: Date;
}
